### PR TITLE
fix: add file interface from  fastify multer

### PR DESCRIPTION
**Pull request by rubiin**

### CODE REVIEW

**Comment by jmcdo29** [comment]
Looks good to me. Can you run `pnpm changeset` and follow the wizard to make a `patch ` for this library?

**Comment by rubiin** [comment]
> Looks good to me. Can you run `pnpm changeset` and follow the wizard to make a `patch ` for this library?

sure thing. Also I wanted to export all the interfaces from `fastify-multer` from the package itself so I dont have to install 
 `fastify-multer` just for the types . How does that sound? @jmcdo29

**Comment by jmcdo29** [comment]
> > Looks good to me. Can you run `pnpm changeset` and follow the wizard to make a `patch ` for this library?
> 
> sure thing. Also I wanted to export all the interfaces from `fastify-multer` from the package itself so I dont have to install `fastify-multer` just for the types . How does that sound? @jmcdo29

Yeah, I think that would be good

**Comment by rubiin** [comment]
cool . I will do that in next PR , LGTM

**Comment by jmcdo29** [comment]
Go ahead and make the next PR too. I'll merge it in before going through with the versioning so that it only has one version change

**Pull request merged**
